using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Rahiq.Infrastructure.Common.Outbox;
using Rahiq.SharedKernel;

namespace Rahiq.Infrastructure.Common.Persistence;

/// <summary>Each module adds its entity mappings through one of these (ADR-012).</summary>
public interface IModelContributor
{
    void Configure(ModelBuilder modelBuilder);
}

/// <summary>
/// One DbContext for the whole application, composed from module contributions. Tables live in each module's
/// schema and are created by SQL migrations, never by EF. Domain events are written to the outbox in the
/// same SaveChanges, so an event exists if and only if its change was committed.
/// </summary>
public sealed class RahiqDbContext(DbContextOptions<RahiqDbContext> options, IEnumerable<IModelContributor> contributors)
    : DbContext(options)
{
    private readonly List<IDomainEvent> _pendingEvents = [];

    public DbSet<OutboxMessage> OutboxMessages => Set<OutboxMessage>();

    public DbSet<AuditEntry> AuditEntries => Set<AuditEntry>();

    internal void Enqueue(IDomainEvent domainEvent) => _pendingEvents.Add(domainEvent);

    public override async Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
    {
        var aggregates = ChangeTracker.Entries<IHasDomainEvents>()
            .Select(e => e.Entity)
            .Where(e => e.DomainEvents.Count > 0)
            .ToList();

        var events = aggregates.SelectMany(a => a.DomainEvents).Concat(_pendingEvents).ToList();
        aggregates.ForEach(a => a.ClearDomainEvents());
        _pendingEvents.Clear();

        foreach (var domainEvent in events)
        {
            OutboxMessages.Add(OutboxMessage.From(domainEvent));
        }

        return await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OutboxMessage>(b =>
        {
            b.ToTable("outbox_messages", "infra");
            b.HasKey(x => x.Id);
            b.Property(x => x.Payload).HasColumnType("jsonb");
        });

        modelBuilder.Entity<AuditEntry>(b =>
        {
            b.ToTable("audit_log", "infra");
            b.HasKey(x => x.Id);
            b.Property(x => x.Id).UseIdentityByDefaultColumn();
            b.Property(x => x.Data).HasColumnType("jsonb");
        });

        foreach (var contributor in contributors)
        {
            contributor.Configure(modelBuilder);
        }

        // Keys are UUID v7 generated by the application: a child added to an aggregate's collection is new, never "modified".
        foreach (var key in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetKeys()).Where(k => k.IsPrimaryKey()))
        {
            foreach (var property in key.Properties.Where(p => p.ClrType == typeof(Guid)))
            {
                property.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never;
            }
        }
    }
}

public sealed class AuditEntry
{
    public long Id { get; init; }

    public Guid? ActorId { get; init; }

    public string? ActorEmail { get; init; }

    public required string Action { get; init; }

    public required string Entity { get; init; }

    public string? EntityId { get; init; }

    public string? Data { get; init; }

    public DateTimeOffset At { get; init; }
}

public static class JsonDefaults
{
    public static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web)
    {
        Converters = { new System.Text.Json.Serialization.JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
