-- Rahiq initial schema (data-model.md, ADR-012, ADR-016, ADR-017).
-- Money: bigint in the smallest unit + char(3) currency. Times: timestamptz (UTC). Keys: uuid v7 from the app.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE SCHEMA IF NOT EXISTS infra;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS pricing;
CREATE SCHEMA IF NOT EXISTS cart;
CREATE SCHEMA IF NOT EXISTS ordering;
CREATE SCHEMA IF NOT EXISTS payments;
CREATE SCHEMA IF NOT EXISTS shipping;
CREATE SCHEMA IF NOT EXISTS customers;
CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS documents;
CREATE SCHEMA IF NOT EXISTS notifications;

-- Rows in append-only tables can never be changed or removed, even by a bug (security.md §6, data-model.md §7).
CREATE OR REPLACE FUNCTION infra.forbid_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'table %.% is append-only', TG_TABLE_SCHEMA, TG_TABLE_NAME;
END $$;

-- ───────────────────────────── infra ─────────────────────────────
CREATE TABLE infra.outbox_messages (
  id uuid PRIMARY KEY,
  type text NOT NULL,
  payload jsonb NOT NULL,
  occurred_at timestamptz NOT NULL,
  processed_at timestamptz,
  attempts int NOT NULL DEFAULT 0,
  next_attempt_at timestamptz,
  last_error text
);
CREATE INDEX ix_outbox_pending ON infra.outbox_messages (occurred_at) WHERE processed_at IS NULL;

CREATE TABLE infra.outbox_consumers (
  message_id uuid NOT NULL,
  consumer text NOT NULL,
  processed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, consumer)
);

CREATE TABLE infra.idempotency_keys (
  scope text NOT NULL,
  key text NOT NULL,
  request_hash text NOT NULL,
  status_code int,
  response_body jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  PRIMARY KEY (scope, key)
);

CREATE TABLE infra.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid,
  actor_email text,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id text,
  data jsonb,
  at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_entity ON infra.audit_log (entity, entity_id);
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON infra.audit_log
  FOR EACH ROW EXECUTE FUNCTION infra.forbid_change();

-- ───────────────────────────── catalog ─────────────────────────────
CREATE TABLE catalog.products (
  id uuid PRIMARY KEY,
  section text NOT NULL CHECK (section IN ('perfume','honey','shared')),
  type text NOT NULL CHECK (type IN ('perfume','attar','hair_home_mist','discovery_set','honey','comb_honey','nuts_in_honey','honey_blend','gift_box','bundle')),
  slug text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('draft','active','archived')),
  attributes jsonb NOT NULL DEFAULT '{}',
  warnings text[] NOT NULL DEFAULT '{}',
  allergens text[] NOT NULL DEFAULT '{}',
  is_featured boolean NOT NULL DEFAULT false,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);
CREATE INDEX ix_products_section_status ON catalog.products (section, status);
CREATE INDEX ix_products_attributes ON catalog.products USING gin (attributes jsonb_path_ops);

CREATE TABLE catalog.product_translations (
  product_id uuid NOT NULL REFERENCES catalog.products(id) ON DELETE CASCADE,
  locale text NOT NULL CHECK (locale IN ('tr','ar','en')),
  name text NOT NULL,
  short_description text,
  story text,
  usage text,
  seo_title text,
  seo_description text,
  PRIMARY KEY (product_id, locale)
);

-- Old slugs keep working with a 301 (content-seo.md §3).
CREATE TABLE catalog.slug_redirects (
  old_slug text PRIMARY KEY,
  product_id uuid NOT NULL REFERENCES catalog.products(id) ON DELETE CASCADE
);

CREATE TABLE catalog.variants (
  id uuid PRIMARY KEY,
  product_id uuid NOT NULL REFERENCES catalog.products(id),
  sku text NOT NULL UNIQUE,
  volume_ml int CHECK (volume_ml > 0),
  weight_g int CHECK (weight_g > 0),
  gtin text,
  shipping_weight_g int NOT NULL CHECK (shipping_weight_g > 0),
  shipping_class text NOT NULL CHECK (shipping_class IN ('standard','fragile','liquid','flammable')),
  is_sample boolean NOT NULL DEFAULT false,
  -- 'batches': own stock. 'components': a bundle whose stock is its parts (product-domain.md §4.3).
  stock_mode text NOT NULL DEFAULT 'batches' CHECK (stock_mode IN ('batches','components')),
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  CHECK (volume_ml IS NOT NULL OR weight_g IS NOT NULL OR stock_mode = 'components')
);
CREATE INDEX ix_variants_product ON catalog.variants (product_id);

-- Fixed bundles: which variants a bundle variant contains.
CREATE TABLE catalog.bundle_items (
  bundle_variant_id uuid NOT NULL REFERENCES catalog.variants(id) ON DELETE CASCADE,
  component_variant_id uuid NOT NULL REFERENCES catalog.variants(id),
  qty int NOT NULL CHECK (qty > 0),
  PRIMARY KEY (bundle_variant_id, component_variant_id)
);

-- Gift box templates: slots the customer fills (e.g. one perfume + one honey).
CREATE TABLE catalog.gift_box_slots (
  product_id uuid NOT NULL REFERENCES catalog.products(id) ON DELETE CASCADE,
  code text NOT NULL,
  allowed_sections text[] NOT NULL,
  required boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  PRIMARY KEY (product_id, code)
);

CREATE TABLE catalog.media (
  id uuid PRIMARY KEY,
  product_id uuid NOT NULL REFERENCES catalog.products(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('catalog','detail','scale','packaging','mood')),
  storage_key text NOT NULL,
  content_type text NOT NULL,
  width int NOT NULL,
  height int NOT NULL,
  -- Law 8: generated or placeholder imagery is flagged and never shown as the product photo.
  is_generated boolean NOT NULL DEFAULT false,
  alt jsonb NOT NULL DEFAULT '{}',
  sort_order int NOT NULL DEFAULT 0,
  CHECK (NOT (is_generated AND role <> 'mood'))
);
CREATE INDEX ix_media_product ON catalog.media (product_id, sort_order);

CREATE TABLE catalog.notes (
  id text PRIMARY KEY,
  family text,
  icon_asset_id uuid,
  names jsonb NOT NULL
);

-- Every time a manager publishes despite a forbidden-term warning (compliance.md §2).
CREATE TABLE catalog.claim_approvals (
  id uuid PRIMARY KEY,
  entity text NOT NULL,
  entity_id uuid NOT NULL,
  terms text[] NOT NULL,
  reason text NOT NULL,
  approved_by uuid NOT NULL,
  approved_at timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER claim_approvals_append_only BEFORE UPDATE OR DELETE ON catalog.claim_approvals
  FOR EACH ROW EXECUTE FUNCTION infra.forbid_change();

-- ───────────────────────────── inventory ─────────────────────────────
CREATE TABLE inventory.batches (
  id uuid PRIMARY KEY,
  variant_id uuid NOT NULL,
  code text NOT NULL,
  qty_received int NOT NULL CHECK (qty_received > 0),
  qty_on_hand int NOT NULL CHECK (qty_on_hand >= 0),
  qty_reserved int NOT NULL DEFAULT 0 CHECK (qty_reserved >= 0),
  produced_at date,
  best_before date,
  origin jsonb,
  lab_report_key text,
  lab_summary jsonb,
  public_token text UNIQUE,
  received_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (variant_id, code),
  -- The last line of defence against overselling: even buggy code cannot reserve what is not there.
  CHECK (qty_reserved <= qty_on_hand),
  CHECK (best_before IS NULL OR produced_at IS NULL OR best_before > produced_at)
);
CREATE INDEX ix_batches_fefo ON inventory.batches (variant_id, best_before NULLS LAST)
  WHERE qty_on_hand > qty_reserved;

CREATE TABLE inventory.reservations (
  id uuid PRIMARY KEY,
  checkout_id uuid NOT NULL,
  order_id uuid,
  batch_id uuid NOT NULL REFERENCES inventory.batches(id),
  variant_id uuid NOT NULL,
  qty int NOT NULL CHECK (qty > 0),
  status text NOT NULL CHECK (status IN ('held','committed','released')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz
);
CREATE INDEX ix_reservations_expiry ON inventory.reservations (expires_at) WHERE status = 'held';
CREATE INDEX ix_reservations_order ON inventory.reservations (order_id);

CREATE TABLE inventory.movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL REFERENCES inventory.batches(id),
  delta int NOT NULL CHECK (delta <> 0),
  reason text NOT NULL CHECK (reason IN ('received','sold','returned','damaged','adjustment')),
  note text,
  ref_id uuid,
  actor_id uuid,
  at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_movements_batch ON inventory.movements (batch_id, at);
CREATE TRIGGER movements_append_only BEFORE UPDATE OR DELETE ON inventory.movements
  FOR EACH ROW EXECUTE FUNCTION infra.forbid_change();

CREATE TABLE inventory.stock_settings (
  variant_id uuid PRIMARY KEY,
  low_stock_threshold int NOT NULL DEFAULT 5 CHECK (low_stock_threshold >= 0),
  requires_expiry boolean NOT NULL DEFAULT false,
  low_stock_alerted_at timestamptz
);

-- ───────────────────────────── pricing ─────────────────────────────
CREATE TABLE pricing.prices (
  variant_id uuid NOT NULL,
  currency char(3) NOT NULL,
  amount bigint NOT NULL CHECK (amount >= 0),
  valid_from timestamptz NOT NULL,
  valid_to timestamptz,
  set_by uuid,
  PRIMARY KEY (variant_id, currency, valid_from),
  CHECK (valid_to IS NULL OR valid_to > valid_from)
);
CREATE UNIQUE INDEX ux_prices_open ON pricing.prices (variant_id, currency) WHERE valid_to IS NULL;

CREATE TABLE pricing.tax_rates (
  category text NOT NULL,
  rate_bp int NOT NULL CHECK (rate_bp BETWEEN 0 AND 10000),
  valid_from date NOT NULL,
  PRIMARY KEY (category, valid_from)
);

CREATE TABLE pricing.coupons (
  id uuid PRIMARY KEY,
  code citext UNIQUE NOT NULL,
  kind text NOT NULL CHECK (kind IN ('percent','fixed','free_shipping')),
  value bigint NOT NULL CHECK (value >= 0),
  currency char(3) NOT NULL DEFAULT 'TRY',
  min_subtotal bigint CHECK (min_subtotal >= 0),
  section text CHECK (section IN ('perfume','honey','shared')),
  max_uses int CHECK (max_uses > 0),
  used_count int NOT NULL DEFAULT 0 CHECK (used_count >= 0),
  per_customer_limit int CHECK (per_customer_limit > 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean NOT NULL DEFAULT true,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (max_uses IS NULL OR used_count <= max_uses),
  CHECK (kind <> 'percent' OR value BETWEEN 1 AND 10000)
);

CREATE TABLE pricing.coupon_redemptions (
  id uuid PRIMARY KEY,
  coupon_id uuid NOT NULL REFERENCES pricing.coupons(id),
  order_id uuid NOT NULL UNIQUE,
  customer_key text NOT NULL,
  status text NOT NULL CHECK (status IN ('held','committed','released')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_redemptions_customer ON pricing.coupon_redemptions (coupon_id, customer_key) WHERE status <> 'released';

-- ───────────────────────────── cart ─────────────────────────────
CREATE TABLE cart.carts (
  id uuid PRIMARY KEY,
  token_hash text NOT NULL UNIQUE,
  customer_id uuid UNIQUE,
  coupon_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);
CREATE INDEX ix_carts_expiry ON cart.carts (expires_at);

CREATE TABLE cart.cart_lines (
  id uuid PRIMARY KEY,
  cart_id uuid NOT NULL REFERENCES cart.carts(id) ON DELETE CASCADE,
  variant_id uuid NOT NULL,
  qty int NOT NULL CHECK (qty > 0),
  components jsonb,
  gift_message text CHECK (length(gift_message) <= 300),
  added_unit_price bigint NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_cart_lines_cart ON cart.cart_lines (cart_id);

-- ───────────────────────────── ordering ─────────────────────────────
CREATE SEQUENCE ordering.order_number_seq START 1;

CREATE TABLE ordering.checkouts (
  id uuid PRIMARY KEY,
  cart_id uuid NOT NULL,
  customer_id uuid,
  email citext,
  phone text,
  shipping_address jsonb,
  billing_address jsonb,
  is_gift boolean NOT NULL DEFAULT false,
  gift_message text CHECK (length(gift_message) <= 300),
  hide_prices boolean NOT NULL DEFAULT false,
  shipping_method text,
  coupon_code text,
  locale text NOT NULL,
  marketing_consent boolean NOT NULL DEFAULT false,
  status text NOT NULL CHECK (status IN ('open','completed','abandoned')),
  order_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ordering.orders (
  id uuid PRIMARY KEY,
  number text NOT NULL UNIQUE,
  checkout_id uuid NOT NULL UNIQUE,
  customer_id uuid,
  email citext NOT NULL,
  phone text,
  status text NOT NULL CHECK (status IN ('pending_payment','confirmed','preparing','shipped','delivered','returned_to_sender','return_requested','returned','refunded','cancelled')),
  payment_method text NOT NULL CHECK (payment_method IN ('card','cod')),
  currency char(3) NOT NULL,
  subtotal bigint NOT NULL CHECK (subtotal >= 0),
  discount bigint NOT NULL CHECK (discount >= 0),
  shipping bigint NOT NULL CHECK (shipping >= 0),
  cod_fee bigint NOT NULL DEFAULT 0 CHECK (cod_fee >= 0),
  tax bigint NOT NULL CHECK (tax >= 0),
  total bigint NOT NULL CHECK (total >= 0),
  shipping_method text NOT NULL,
  shipping_address jsonb NOT NULL,
  billing_address jsonb NOT NULL,
  is_gift boolean NOT NULL DEFAULT false,
  gift_message text,
  hide_prices boolean NOT NULL DEFAULT false,
  coupon_code text,
  locale text NOT NULL,
  contract_doc_hash text NOT NULL,
  fraud_flags text[] NOT NULL DEFAULT '{}',
  placed_at timestamptz NOT NULL,
  reservation_expires_at timestamptz,
  idempotency_key text UNIQUE,
  -- Prices are tax-inclusive; tax is informational and already inside the lines (ADR-017).
  CHECK (total = subtotal - discount + shipping + cod_fee),
  CHECK (discount <= subtotal)
);
CREATE INDEX ix_orders_customer ON ordering.orders (customer_id, placed_at DESC);
CREATE INDEX ix_orders_status ON ordering.orders (status, placed_at);
CREATE INDEX ix_orders_email ON ordering.orders (email);

CREATE TABLE ordering.order_lines (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES ordering.orders(id),
  variant_id uuid NOT NULL,
  product_id uuid NOT NULL,
  sku text NOT NULL,
  section text NOT NULL,
  product_type text NOT NULL,
  name_snapshot text NOT NULL,
  variant_label_snapshot text NOT NULL,
  warnings_snapshot text[] NOT NULL,
  is_sample boolean NOT NULL DEFAULT false,
  shipping_class text NOT NULL,
  group_id uuid,
  group_label_snapshot text,
  unit_price bigint NOT NULL CHECK (unit_price >= 0),
  qty int NOT NULL CHECK (qty > 0),
  discount bigint NOT NULL DEFAULT 0 CHECK (discount >= 0),
  tax_rate_bp int NOT NULL,
  tax_amount bigint NOT NULL CHECK (tax_amount >= 0),
  line_total bigint NOT NULL CHECK (line_total >= 0),
  batch_allocations jsonb,
  returnable boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  CHECK (line_total = unit_price * qty - discount)
);
CREATE INDEX ix_order_lines_order ON ordering.order_lines (order_id);
CREATE INDEX ix_order_lines_batches ON ordering.order_lines USING gin (batch_allocations jsonb_path_ops);

CREATE TABLE ordering.order_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES ordering.orders(id),
  status text NOT NULL,
  note text,
  actor_id uuid,
  at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_order_history_order ON ordering.order_status_history (order_id, at);
CREATE TRIGGER order_history_append_only BEFORE UPDATE OR DELETE ON ordering.order_status_history
  FOR EACH ROW EXECUTE FUNCTION infra.forbid_change();

CREATE TABLE ordering.order_notes (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES ordering.orders(id),
  body text NOT NULL,
  author_id uuid NOT NULL,
  at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ordering.return_requests (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES ordering.orders(id),
  status text NOT NULL CHECK (status IN ('requested','approved','rejected','received','refunded')),
  kind text NOT NULL CHECK (kind IN ('withdrawal','damaged','wrong_item')),
  reason text NOT NULL,
  lines jsonb NOT NULL,
  photo_keys text[] NOT NULL DEFAULT '{}',
  resolution_note text,
  refund_amount bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (kind = 'withdrawal' OR cardinality(photo_keys) > 0)
);
CREATE INDEX ix_returns_order ON ordering.return_requests (order_id);

-- ───────────────────────────── payments ─────────────────────────────
CREATE TABLE payments.payments (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL,
  order_number text NOT NULL,
  provider text NOT NULL,
  provider_ref text,
  session_token text,
  method text NOT NULL CHECK (method IN ('card','cod')),
  amount bigint NOT NULL CHECK (amount >= 0),
  refunded_amount bigint NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0),
  currency char(3) NOT NULL,
  installments int NOT NULL DEFAULT 1 CHECK (installments >= 1),
  status text NOT NULL CHECK (status IN ('pending','succeeded','failed','refunded','partially_refunded','collected_on_delivery')),
  failure_reason text,
  raw_last_event jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (refunded_amount <= amount)
);
CREATE INDEX ix_payments_order ON payments.payments (order_id);
CREATE INDEX ix_payments_pending ON payments.payments (created_at) WHERE status = 'pending';
CREATE UNIQUE INDEX ux_payments_provider_ref ON payments.payments (provider, provider_ref) WHERE provider_ref IS NOT NULL;

CREATE TABLE payments.webhook_events (
  provider text NOT NULL,
  event_id text NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  outcome text,
  payload jsonb NOT NULL,
  PRIMARY KEY (provider, event_id)
);

CREATE TABLE payments.refunds (
  id uuid PRIMARY KEY,
  payment_id uuid NOT NULL REFERENCES payments.payments(id),
  order_id uuid NOT NULL,
  amount bigint NOT NULL CHECK (amount > 0),
  reason text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending','succeeded','failed')),
  provider_ref text,
  requested_by uuid,
  approved_by uuid,
  failure_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);
CREATE INDEX ix_refunds_order ON payments.refunds (order_id);

CREATE TABLE payments.reconciliation_runs (
  id uuid PRIMARY KEY,
  day date NOT NULL,
  provider text NOT NULL,
  status text NOT NULL CHECK (status IN ('clean','discrepancies','failed')),
  discrepancies jsonb NOT NULL DEFAULT '[]',
  ran_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (day, provider)
);

-- ───────────────────────────── shipping ─────────────────────────────
CREATE TABLE shipping.zones (
  code text PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE shipping.provinces (
  code int PRIMARY KEY CHECK (code BETWEEN 1 AND 81),
  name text NOT NULL,
  zone_code text NOT NULL REFERENCES shipping.zones(code)
);

CREATE TABLE shipping.rates (
  zone_code text NOT NULL REFERENCES shipping.zones(code),
  method text NOT NULL,
  max_weight_g int NOT NULL CHECK (max_weight_g > 0),
  amount bigint NOT NULL CHECK (amount >= 0),
  currency char(3) NOT NULL DEFAULT 'TRY',
  PRIMARY KEY (zone_code, method, max_weight_g)
);

CREATE TABLE shipping.settings (
  id int PRIMARY KEY CHECK (id = 1),
  free_shipping_threshold bigint,
  currency char(3) NOT NULL DEFAULT 'TRY'
);

CREATE TABLE shipping.shipments (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL,
  order_number text NOT NULL,
  carrier text NOT NULL,
  tracking_number text,
  tracking_url text,
  label_key text,
  package_photo_key text,
  status text NOT NULL CHECK (status IN ('label_created','handed_over','in_transit','out_for_delivery','delivered','returned','failed')),
  events jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_shipments_order ON shipping.shipments (order_id);
CREATE UNIQUE INDEX ux_shipments_tracking ON shipping.shipments (carrier, tracking_number) WHERE tracking_number IS NOT NULL;

-- ───────────────────────────── customers ─────────────────────────────
CREATE TABLE customers.customers (
  id uuid PRIMARY KEY,
  email citext NOT NULL UNIQUE,
  phone text,
  name text,
  locale text NOT NULL DEFAULT 'tr',
  cod_refusals int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE customers.addresses (
  id uuid PRIMARY KEY,
  customer_id uuid NOT NULL REFERENCES customers.customers(id) ON DELETE CASCADE,
  label text,
  data jsonb NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Append-only: every consent change is a new row, the proof when asked (data-model.md §6).
CREATE TABLE customers.consents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id uuid,
  email citext,
  channel text NOT NULL CHECK (channel IN ('email','sms','call')),
  purpose text NOT NULL CHECK (purpose IN ('marketing')),
  granted boolean NOT NULL,
  source text NOT NULL,
  at timestamptz NOT NULL DEFAULT now(),
  iys_synced_at timestamptz
);
CREATE INDEX ix_consents_customer ON customers.consents (customer_id, channel, at DESC);
CREATE INDEX ix_consents_email ON customers.consents (email, channel, at DESC);

CREATE TABLE customers.otp_codes (
  id uuid PRIMARY KEY,
  email citext NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  attempts int NOT NULL DEFAULT 0,
  consumed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_otp_email ON customers.otp_codes (email, created_at DESC);

CREATE TABLE customers.staff_users (
  id uuid PRIMARY KEY,
  email citext NOT NULL UNIQUE,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('owner','manager','content','fulfillment','support')),
  password_hash text NOT NULL,
  totp_secret_protected text,
  totp_enabled boolean NOT NULL DEFAULT false,
  failed_attempts int NOT NULL DEFAULT 0,
  locked_until timestamptz,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz
);

CREATE TABLE customers.refresh_tokens (
  id uuid PRIMARY KEY,
  family_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  subject_kind text NOT NULL CHECK (subject_kind IN ('customer','staff')),
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  used_at timestamptz,
  revoked_at timestamptz
);
CREATE INDEX ix_refresh_family ON customers.refresh_tokens (family_id);

-- ───────────────────────────── content ─────────────────────────────
CREATE TABLE content.pages (
  id uuid PRIMARY KEY,
  slug text NOT NULL,
  locale text NOT NULL CHECK (locale IN ('tr','ar','en')),
  kind text NOT NULL CHECK (kind IN ('legal','story','guide','faq')),
  title text NOT NULL,
  summary text,
  body_markdown text NOT NULL,
  status text NOT NULL CHECK (status IN ('draft','published')),
  related_product_ids uuid[] NOT NULL DEFAULT '{}',
  updated_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  UNIQUE (slug, locale)
);

-- ───────────────────────────── documents ─────────────────────────────
CREATE TABLE documents.documents (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind IN ('pre_information','distance_sales')),
  locale text NOT NULL,
  html text NOT NULL,
  sha256 text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (order_id, kind)
);

CREATE TABLE documents.invoices (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL,
  order_number text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('sale','refund')),
  reference text NOT NULL UNIQUE,
  provider text NOT NULL,
  provider_ref text,
  invoice_number text,
  pdf_url text,
  status text NOT NULL CHECK (status IN ('pending','issued','failed')),
  amount bigint NOT NULL,
  attempts int NOT NULL DEFAULT 0,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  issued_at timestamptz
);
CREATE INDEX ix_invoices_pending ON documents.invoices (created_at) WHERE status <> 'issued';

-- ───────────────────────────── notifications ─────────────────────────────
CREATE TABLE notifications.log (
  id uuid PRIMARY KEY,
  channel text NOT NULL CHECK (channel IN ('email','sms','whatsapp')),
  template text NOT NULL,
  recipient_masked text NOT NULL,
  ref_id uuid,
  -- One message per business fact: a webhook arriving five times still sends one email.
  dedupe_key text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('sent','failed','skipped')),
  error text,
  at timestamptz NOT NULL DEFAULT now()
);
