-- Reference data. EVERY VALUE HERE IS PROVISIONAL (ADR-011):
--   tax rates: confirm each category with the accountant (Mali Müşavir) before launch;
--   zones and rates: replace with the signed carrier contract. The warehouse is assumed to be in İstanbul.

-- KDV by tax category, in basis points (1000 = 10%). Categories come from the product type.
INSERT INTO pricing.tax_rates (category, rate_bp, valid_from) VALUES
  ('food', 100, '2024-01-01'),
  ('cosmetics', 2000, '2024-01-01'),
  ('packaging', 2000, '2024-01-01'),
  ('services', 2000, '2024-01-01'); -- shipping and the cash-on-delivery fee

INSERT INTO shipping.zones (code, name) VALUES
  ('near', 'Marmara'),
  ('mid', 'Central, Aegean, Mediterranean, Black Sea'),
  ('far', 'Eastern and South-eastern Anatolia');

-- The 81 provinces by plate code (address form: province, then district).
INSERT INTO shipping.provinces (code, name, zone_code) VALUES
  (1, $$Adana$$, $$mid$$),
  (2, $$Adıyaman$$, $$far$$),
  (3, $$Afyonkarahisar$$, $$mid$$),
  (4, $$Ağrı$$, $$far$$),
  (5, $$Amasya$$, $$mid$$),
  (6, $$Ankara$$, $$mid$$),
  (7, $$Antalya$$, $$mid$$),
  (8, $$Artvin$$, $$mid$$),
  (9, $$Aydın$$, $$mid$$),
  (10, $$Balıkesir$$, $$near$$),
  (11, $$Bilecik$$, $$near$$),
  (12, $$Bingöl$$, $$far$$),
  (13, $$Bitlis$$, $$far$$),
  (14, $$Bolu$$, $$mid$$),
  (15, $$Burdur$$, $$mid$$),
  (16, $$Bursa$$, $$near$$),
  (17, $$Çanakkale$$, $$near$$),
  (18, $$Çankırı$$, $$mid$$),
  (19, $$Çorum$$, $$mid$$),
  (20, $$Denizli$$, $$mid$$),
  (21, $$Diyarbakır$$, $$far$$),
  (22, $$Edirne$$, $$near$$),
  (23, $$Elazığ$$, $$far$$),
  (24, $$Erzincan$$, $$far$$),
  (25, $$Erzurum$$, $$far$$),
  (26, $$Eskişehir$$, $$mid$$),
  (27, $$Gaziantep$$, $$far$$),
  (28, $$Giresun$$, $$mid$$),
  (29, $$Gümüşhane$$, $$mid$$),
  (30, $$Hakkari$$, $$far$$),
  (31, $$Hatay$$, $$mid$$),
  (32, $$Isparta$$, $$mid$$),
  (33, $$Mersin$$, $$mid$$),
  (34, $$İstanbul$$, $$near$$),
  (35, $$İzmir$$, $$mid$$),
  (36, $$Kars$$, $$far$$),
  (37, $$Kastamonu$$, $$mid$$),
  (38, $$Kayseri$$, $$mid$$),
  (39, $$Kırklareli$$, $$near$$),
  (40, $$Kırşehir$$, $$mid$$),
  (41, $$Kocaeli$$, $$near$$),
  (42, $$Konya$$, $$mid$$),
  (43, $$Kütahya$$, $$mid$$),
  (44, $$Malatya$$, $$far$$),
  (45, $$Manisa$$, $$mid$$),
  (46, $$Kahramanmaraş$$, $$mid$$),
  (47, $$Mardin$$, $$far$$),
  (48, $$Muğla$$, $$mid$$),
  (49, $$Muş$$, $$far$$),
  (50, $$Nevşehir$$, $$mid$$),
  (51, $$Niğde$$, $$mid$$),
  (52, $$Ordu$$, $$mid$$),
  (53, $$Rize$$, $$mid$$),
  (54, $$Sakarya$$, $$near$$),
  (55, $$Samsun$$, $$mid$$),
  (56, $$Siirt$$, $$far$$),
  (57, $$Sinop$$, $$mid$$),
  (58, $$Sivas$$, $$mid$$),
  (59, $$Tekirdağ$$, $$near$$),
  (60, $$Tokat$$, $$mid$$),
  (61, $$Trabzon$$, $$mid$$),
  (62, $$Tunceli$$, $$far$$),
  (63, $$Şanlıurfa$$, $$far$$),
  (64, $$Uşak$$, $$mid$$),
  (65, $$Van$$, $$far$$),
  (66, $$Yozgat$$, $$mid$$),
  (67, $$Zonguldak$$, $$mid$$),
  (68, $$Aksaray$$, $$mid$$),
  (69, $$Bayburt$$, $$mid$$),
  (70, $$Karaman$$, $$mid$$),
  (71, $$Kırıkkale$$, $$mid$$),
  (72, $$Batman$$, $$far$$),
  (73, $$Şırnak$$, $$far$$),
  (74, $$Bartın$$, $$mid$$),
  (75, $$Ardahan$$, $$far$$),
  (76, $$Iğdır$$, $$far$$),
  (77, $$Yalova$$, $$near$$),
  (78, $$Karabük$$, $$mid$$),
  (79, $$Kilis$$, $$far$$),
  (80, $$Osmaniye$$, $$mid$$),
  (81, $$Düzce$$, $$mid$$);

-- Weight bands in grams; the first band whose max_weight_g covers the parcel applies. Amounts in kuruş.
INSERT INTO shipping.rates (zone_code, method, max_weight_g, amount) VALUES
  ($$near$$, $$standard$$, 2000, 8990),
  ($$near$$, $$standard$$, 5000, 11990),
  ($$near$$, $$standard$$, 10000, 15990),
  ($$near$$, $$standard$$, 30000, 24990),
  ($$mid$$, $$standard$$, 2000, 9990),
  ($$mid$$, $$standard$$, 5000, 12990),
  ($$mid$$, $$standard$$, 10000, 16990),
  ($$mid$$, $$standard$$, 30000, 25990),
  ($$far$$, $$standard$$, 2000, 10990),
  ($$far$$, $$standard$$, 5000, 13990),
  ($$far$$, $$standard$$, 10000, 17990),
  ($$far$$, $$standard$$, 30000, 26990);

-- Free standard shipping from 1,500.00 TRY (configurable in admin).
INSERT INTO shipping.settings (id, free_shipping_threshold, currency) VALUES (1, 150000, 'TRY');
