-- Conversations (CRM + messaging channels + AI agent). See docs/adr/019-conversations-and-agent.md.
-- Personal data (KVKK): contacts and messages are erased with the customer (CustomerDataErased).

CREATE SCHEMA IF NOT EXISTS crm;

-- ───────────────────────────── crm ─────────────────────────────
-- One row per person per channel (a Telegram user, a WhatsApp number, an Instagram account...).
-- customer_id links to a store account once staff (or a future sign-in flow) matches them.
CREATE TABLE crm.contacts (
  id uuid PRIMARY KEY,
  channel text NOT NULL CHECK (channel IN ('telegram','messenger','instagram','whatsapp')),
  external_id text NOT NULL,
  display_name text,
  phone text,
  locale text,
  customer_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  erased_at timestamptz,
  UNIQUE (channel, external_id)
);
CREATE INDEX ix_contacts_customer ON crm.contacts (customer_id) WHERE customer_id IS NOT NULL;

-- A thread with one contact. mode = who answers: the AI agent or a person.
-- The agent runs while agent_pending_seq > agent_done_seq; the lease stops two workers taking the same thread.
CREATE TABLE crm.conversations (
  id uuid PRIMARY KEY,
  contact_id uuid NOT NULL REFERENCES crm.contacts(id) ON DELETE CASCADE,
  channel text NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
  mode text NOT NULL DEFAULT 'agent' CHECK (mode IN ('agent','human')),
  assigned_staff_id uuid,
  handoff_reason text,
  handoff_at timestamptz,
  unread int NOT NULL DEFAULT 0 CHECK (unread >= 0),
  last_message_at timestamptz NOT NULL DEFAULT now(),
  last_inbound_at timestamptz,
  last_preview text,
  agent_pending_seq bigint NOT NULL DEFAULT 0,
  agent_done_seq bigint NOT NULL DEFAULT 0,
  agent_lease_until timestamptz,
  agent_attempts int NOT NULL DEFAULT 0,
  agent_retry_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (agent_done_seq <= agent_pending_seq)
);
-- At most one conversation per contact: a closed one is reopened by the next message.
CREATE UNIQUE INDEX ux_conversations_contact ON crm.conversations (contact_id);
CREATE INDEX ix_conversations_inbox ON crm.conversations (status, last_message_at DESC);
CREATE INDEX ix_conversations_agent_due ON crm.conversations (last_inbound_at)
  WHERE mode = 'agent' AND status = 'open' AND agent_pending_seq > agent_done_seq;

-- Every message, with the channel it came from or went to. external_id deduplicates provider retries
-- (Meta and Telegram resend a webhook they think was not received).
CREATE TABLE crm.messages (
  id uuid PRIMARY KEY,
  conversation_id uuid NOT NULL REFERENCES crm.conversations(id) ON DELETE CASCADE,
  channel text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('in','out')),
  author text NOT NULL CHECK (author IN ('customer','agent','staff','system')),
  staff_id uuid,
  kind text NOT NULL DEFAULT 'text',
  body text NOT NULL,
  external_id text,
  status text NOT NULL DEFAULT 'received' CHECK (status IN ('received','pending','sent','failed','note')),
  attempts int NOT NULL DEFAULT 0,
  next_attempt_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);
CREATE UNIQUE INDEX ux_messages_external ON crm.messages (channel, external_id) WHERE external_id IS NOT NULL AND direction = 'in';
CREATE INDEX ix_messages_conversation ON crm.messages (conversation_id, created_at);
CREATE INDEX ix_messages_outbox ON crm.messages (next_attempt_at NULLS FIRST) WHERE status = 'pending';

-- What the agent did with its tools (audit, cost control, abuse limits).
CREATE TABLE crm.agent_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id uuid NOT NULL REFERENCES crm.conversations(id) ON DELETE CASCADE,
  tool text NOT NULL,
  input jsonb NOT NULL,
  ok boolean NOT NULL,
  at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_agent_actions_conversation ON crm.agent_actions (conversation_id, tool, at DESC);

-- ───────────────────────────── cart: hand-off links ─────────────────────────────
-- A cart prepared in a chat is claimed once through a short-lived link; only the code's hash is stored.
ALTER TABLE cart.carts ADD COLUMN handoff_code_hash text UNIQUE;
ALTER TABLE cart.carts ADD COLUMN handoff_expires_at timestamptz;
