<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Rahiq.Infrastructure.Common\Rahiq.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\Rahiq.Modules.Content.Contracts\Rahiq.Modules.Content.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Rahiq.Domain.Tests" />
    <InternalsVisibleTo Include="Rahiq.CommerceTests" />
    <InternalsVisibleTo Include="Rahiq.IntegrationTests" />
    <InternalsVisibleTo Include="Rahiq.Testing" />
    <InternalsVisibleTo Include="Rahiq.Api" />
  </ItemGroup>
</Project>
